### ISSUE TITLE
fails to npm install with node v12.7.0

### ISSUE THREAD

**Issue by lacmuch** [Salakar/crc16#1]
It fails to build with node v12.7.0:

../lib/crc16.cc: In function 'void CRC16::Main(const v8::FunctionCallbackInfo<v8::Value>&)':
../lib/crc16.cc:70:49: error: no matching function for call to 'v8::Value::ToObject()'
     Local<Object> bufferObj = args[0]->ToObject();

**Comment by emrealparslan93** [comment]
I'm having this issue too.

      Installing node modules (package.json)
       
       > crc16@1.0.1 install /app/node_modules/crc16
       > node-gyp rebuild
       
       make: Entering directory '/app/node_modules/crc16/build'
         CXX(target) Release/obj.target/crc16/lib/crc16.o
       ../lib/crc16.cc: In function 'void CRC16::Main(const v8::FunctionCallbackInfo<v8::Value>&)':
       ../lib/crc16.cc:70:49: error: no matching function for call to 'v8::Value::ToObject()'
            Local<Object> bufferObj = args[0]->ToObject();
                                                        ^
       In file included from /app/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                        from ../lib/crc16.cc:1:
       /app/.cache/node-gyp/12.13.0/include/node/v8.h:2576:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
          V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                                   ^~~~~~~~
       /app/.cache/node-gyp/12.13.0/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
       In file included from /app/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                        from /app/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                        from /app/.cache/node-gyp/12.13.0/include/node/node.h:63,
                        from ../lib/crc16.cc:1:
       /app/.cache/node-gyp/12.13.0/include/node/v8.h:2590:31: note: candidate: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                        Local<Object> ToObject(Isolate* isolate) const);
                                      ^
       /app/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       /app/.cache/node-gyp/12.13.0/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
                        Local<Object> ToObject(Isolate* isolate) const);
                                      ^
       /app/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       ../lib/crc16.cc:78:109: warning: 'static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)' is deprecated: Use maybe version [-Wdeprecated-declarations]
                    Exception::TypeError(String::NewFromUtf8(isolate, "Invalid arguments provided. Buffer required."))
                                                                                                                    ^
       In file included from /app/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                        from /app/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                        from /app/.cache/node-gyp/12.13.0/include/node/node.h:63,
                        from ../lib/crc16.cc:1:
       /app/.cache/node-gyp/12.13.0/include/node/v8.h:2936:21: note: declared here
              Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                            ^
       /app/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       ../lib/crc16.cc:84:105: warning: 'static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)' is deprecated: Use maybe version [-Wdeprecated-declarations]
                Exception::TypeError(String::NewFromUtf8(isolate, "Invalid arguments provided. Buffer required."))
                                                                                                                ^
       In file included from /app/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                        from /app/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                        from /app/.cache/node-gyp/12.13.0/include/node/node.h:63,
                        from ../lib/crc16.cc:1:
       /app/.cache/node-gyp/12.13.0/include/node/v8.h:2936:21: note: declared here
              Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                            ^
       /app/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       crc16.target.mk:107: recipe for target 'Release/obj.target/crc16/lib/crc16.o' failed
       make: *** [Release/obj.target/crc16/lib/crc16.o] Error 1
       make: Leaving directory '/app/node_modules/crc16/build'`

**Comment by heathcliff-hu** [comment]
+1

**Comment by MitchellMonaghan** [comment]
+1

**Comment by BGOnline-CN** [comment]
+1 v12.13.1

**Comment by jesusx21** [comment]
+1

**Comment by Salakar** [comment]
I would recommend seeking alternatives, I don't have the time right now to upgrade this to work with latest node versions.

Having said that I'd welcome and help get a PR reviewed, merged & released if someone sent one over
